import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <main
          className={`dark text-foreground bg-background ${inter.className}`}
        >
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </main>
        <div
          id="snackbar"
          className="fixed  opacity-0  p-2 text-xs font-bold text-white bg-black rounded transition-all duration-500 ease-in-out  z-50 bottom-4 left-2/4"
        ></div>
      </body>
    </html>
  );
}
